# Generated by Django 4.0.4 on 2022-05-31 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('tg_name', models.CharField(default='Anon', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TgMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook_telegram.tguser')),
            ],
        ),
    ]
