# Generated by Django 4.0.4 on 2022-06-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessage',
            name='from_id',
            field=models.IntegerField(),
        ),
    ]
