# Generated by Django 4.0.4 on 2022-06-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_telegram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='tg_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tguser',
            old_name='tg_id',
            new_name='user_id',
        ),
    ]
