# Generated by Django 4.0.4 on 2022-06-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_telegram', '0004_alter_tgmessage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(default=True)),
                ('from_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TgMessage',
        ),
    ]
