# Generated by Django 4.0.4 on 2022-06-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
